// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial3_LondonoValenciaSebastian.DAL;

#nullable disable

namespace Concert.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Parcial3_LondonoValenciaSebastian.DAL.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntranceGate")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00402047-278b-427c-a62a-2ab6f837139f"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("f9d20d0e-f10e-436c-b834-352bb80e2a98"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("1a5cdf59-51e5-4106-8ddd-0e0f13eeee1b"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("7110ffb5-e0d5-48a1-bb21-c6bbb5538bbc"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("0da9321c-43b4-4ccd-871b-727dd6f80602"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("e52acc46-1c62-485c-bde4-793e1d6bbbac"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("0e0c0e94-a138-4979-b6b4-d6f7dc29f61d"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("bc58a26e-fdcc-4125-aa0b-ea810baae223"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("6e6205e1-78fe-407d-934a-19a731aa6772"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("16ccc9d0-02a1-4ca3-9520-75316844e84b"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("ed36bf12-4c66-4d33-b334-5ed83fe04806"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("8c2b831e-da98-408e-bea4-6ff65a8d76ae"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("b1f15497-fe5b-4925-a722-d780333acbfd"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("a1d080b1-2db0-4b47-a803-4945ac7a7627"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("d928f9e6-9ae3-42fb-bf85-2615be572b14"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("052bab52-42e6-40b7-a53d-465ae29105df"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("b5baca16-ffdf-44a5-b55f-48bb09652cab"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("15d13579-9ba0-41ec-8fe8-968c6f66bc1a"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("034930b5-f737-484c-86dd-f298ebdc9d8f"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("4871b819-992a-4f36-95aa-dcd20251c324"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("f656fe07-bc6e-4c78-a887-e698b47f528b"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("4688d5fa-d564-4848-9990-f12a53fcb5e2"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("41edf72a-5fe1-4375-a9f7-1524009572ac"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("07770e38-08c1-4046-8c31-91c5f52597c5"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("2f24fcfb-b81f-4caa-9080-f896a0f89703"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("985d9082-2d10-42b4-b9f1-9e998c5bea1d"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("742913f5-49f2-486c-948f-f82e338c3415"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("24e584e2-3e9e-44ba-82be-c619e5f1af42"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("f68cdb7f-f07a-4a13-9abf-4448837486f5"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("a300bfc8-7c1a-4a3d-9ace-aee8eb05fb12"),
                            IsUsed = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
